### PR TITLE
update spoke template to support multi-region

### PR DESCRIPTION
**Pull request by reaperharvest**
update the hard coded us-east-1 references to support multi-region event/deploys

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gsingh04** [comment]
Thanks for your feedback. The solution supports only **us-east-1** deployments. This is because the solution is built on CloudWatch events rule and Trusted Advisor checks integration which is only available in us-east-1. Though you deploy only in us-east-1 but the solution monitors all regions, such is the nature of Trusted Advisor checks.
Reference [here](https://docs.aws.amazon.com/solutions/latest/limit-monitor/deployment.html)

**Comment by reaperharvest** [comment]
@gsingh04 ah yes this is true, I instinctively deploy to all of our regions. But there is another cloudwatch event pattern it is watching for too right? I believe it comes from the lambda function that checks service quotes for the ec2 cpu limits? Would that be coming from a different region since service quotas is regional?

**Comment by gsingh04** [comment]
Yes, it there is a separate patter for service quota ec2 cpu limit. As you can see it will monitor all regions: 
https://github.com/awslabs/aws-limit-monitor/blob/1f365564eae725aeac994bbbd5b2895d76c30332/source/services/servicequotaschecks/lib/service-quotas-checks.js#L42
And it will push event on the event bus:
https://github.com/awslabs/aws-limit-monitor/blob/1f365564eae725aeac994bbbd5b2895d76c30332/source/services/servicequotaschecks/lib/service-quotas-checks.js#L252

Hope this answers your query.

**Comment by reaperharvest** [comment]
Thanks for the clarification. Closing pull request

**Pull request closed without merging**
